Fix for gentooLTO/issues/#592 (#596)
Closes gentooLTO/issues/#592

Without it when compiling an impossible optimization breaks the process

error: inlining failed in call to ‘always_inline’ ‘vasprintf.localalias’: function not inlinable

Co-authored-by: Jorge Millán <jbcjorge@trackstreet.com>