Fix for gentooLTO/issues/#592
Closes gentooLTO/issues/#592

Without it when compiling an impossible optimization breaks the process

error: inlining failed in call to ‘always_inline’ ‘vasprintf.localalias’: function not inlinable