media-libs/ilmbase: -lrt needed to build openexr
Building media-libs/openexr with LTO fails with:

> /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib32/libIlmThread.so: undefined reference to `pthread_create'
> /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib32/libIlmThread.so: undefined reference to `sem_wait'
> /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib32/libIlmThread.so: undefined reference to `sem_init'
> /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib32/libIlmThread.so: undefined reference to `sem_destroy'
> /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib32/libIlmThread.so: undefined reference to `sem_getvalue'
> /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib32/libIlmThread.so: undefined reference to `sem_post'
> /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib32/libIlmThread.so: undefined reference to `sem_trywait'

if media-libs/ilmbase was built without -lrt