sys-devel/llvm: added `-fno-finite-math-only` workaround (#515)
* Added -ffinite-math-only workaround for llvm 10+. Without it, clang 10 fails to emerge with error ``undefined reference to `__log10_finite'``.

* Minor change to workaround comment.